-- First, get the act ID
DO $$
DECLARE
    act_id UUID;
BEGIN
    -- Insert or get the act
    INSERT INTO law_acts (act_name, act_year, short_title, category, preamble, tags)
    VALUES ('Hindu Marriage Act', 1955, 'HMA', 'FAMILY_LAW', 
            'An Act to amend and codify the law relating to marriage among Hindus.',
            ARRAY['FAMILY_LAW', 'MARRIAGE'])
    ON CONFLICT (act_name, act_year) 
    DO UPDATE SET short_title = EXCLUDED.short_title
    RETURNING id INTO act_id;
    
    -- Insert main sections
    INSERT INTO law_sections (act_id, section_number, section_title, section_text) VALUES
    (act_id, '1', 'Short title and extent', 'This Act may be called the Hindu Marriage Act, 1955. It extends to the whole of India except the State of Jammu and Kashmir, and applies also to Hindus domiciled in the territories to which this Act extends who are outside the said territories.'),
    
    (act_id, '2', 'Application of Act', 'This Act applies to any person who is a Hindu by religion in any of its forms or developments, including a Virashaiva, a Lingayat or a follower of the Brahmo, Prarthana or Arya Samaj; to any person who is a Buddhist, Jaina or Sikh by religion; and to any other person domiciled in the territories to which this Act extends who is not a Muslim, Christian, Parsi or Jew by religion.'),
    
    (act_id, '3', 'Definitions', 'In this Act, unless the context otherwise requires, (a) the expressions "custom" and "usage" signify any rule which, having been continuously and uniformly observed for a long time, has obtained the force of law among Hindus in any local area, tribe, community, group or family: Provided that the rule is certain and not unreasonable or opposed to public policy; and Provided further that in the case of a rule applicable only to a family it has not been discontinued by the family; (b) "district court" means the principal civil court of original jurisdiction, and includes any other civil court which may be specified by the State Government by notification in the Official Gazette as having jurisdiction in respect of the matters dealt with in this Act; (c) "full blood" and "half blood" – two persons are said to be related to each other by full blood when they are descended from a common ancestor by the same wife and by half blood when they are descended from a common ancestor but by different wives; (d) "uterine blood" – two persons are said to be related to each other by uterine blood when they are descended from a common ancestress but by different husbands; (e) "prescribed" means prescribed by rules made under this Act; (f) (i) "sapinda relationship" with reference to any person extends as far as the third generation (inclusive) in the line of ascent through the mother, and the fifth (inclusive) in the line of ascent through the father, the line being traced upwards in each case from the person concerned, who is to be counted as the first generation; (ii) two persons are said to be "sapindas" of each other if one is a lineal ascendant of the other within the limits of sapinda relationship, or if they have a common lineal ascendant who is within the limits of sapinda relationship with reference to each of them; (g) "degrees of prohibited relationship" – two persons are said to be within the "degrees of prohibited relationship" – (i) if one is a lineal ascendant of the other; or (ii) if one was the wife or husband of a lineal ascendant or descendant of the other; or (iii) if one was the wife of the brother or of the father’s or mother’s brother or of the grandfather’s or grandmother’s brother of the other; or (iv) if the two are brother and sister, uncle and niece, aunt and nephew, or children of brother and sister or of two brothers or of two sisters. Explanation – For the purposes of clauses (f) and (g), relationship includes – (i) relationship by half or uterine blood as well as by full blood; (ii) illegitimate blood relationship as well as legitimate; (iii) relationship by adoption as well as by blood; and all terms of relationship in those clauses shall be construed accordingly.'),
    
    (act_id, '4', 'Overriding effect of Act', 'Save as otherwise expressly provided in this Act, any text, rule or interpretation of Hindu law or any custom or usage as part of that law in force immediately before the commencement of this Act shall cease to have effect with respect to any matter for which provision is made in this Act; and any other law in force immediately before the commencement of this Act shall cease to have effect in so far as it is inconsistent with any of the provisions contained in this Act.'),
    
    (act_id, '5', 'Conditions for a Hindu marriage', 'A marriage may be solemnized between any two Hindus, if the following conditions are fulfilled, namely: (i) neither party has a spouse living at the time of the marriage; (ii) at the time of the marriage, neither party is incapable of giving a valid consent to it in consequence of unsoundness of mind; or though capable of giving a valid consent, has been suffering from mental disorder of such a kind or to such an extent as to be unfit for marriage and the procreation of children; or has been subject to recurrent attacks of insanity or epilepsy; (iii) the bridegroom has completed the age of twenty-one years and the bride the age of eighteen years at the time of the marriage; (iv) the parties are not within the degrees of prohibited relationship unless the custom or usage governing each of them permits of a marriage between the two; (v) the parties are not sapindas of each other, unless the custom or usage governing each of them permits of a marriage between the two.'),
    
    (act_id, '6', 'Guardianship in marriage', '[Repealed by the Child Marriage Restraint (Amendment) Act, 1978, (2 of 1978), section 6 and Schedule]'),
    
    (act_id, '7', 'Ceremonies for a Hindu marriage', 'A Hindu marriage may be solemnized in accordance with the customary rites and ceremonies of either party thereto. Where such rites and ceremonies include the saptapadi (the taking of seven steps by the bridegroom and the bride jointly before the sacred fire), the marriage becomes complete and binding when the seventh step is taken.'),
    
    (act_id, '8', 'Registration of Hindu marriages', 'For the purpose of facilitating the proof of Hindu marriages, the State Government may make rules providing that the parties to any such marriage may have the particulars relating to their marriage entered in such manner and subject to such conditions as may be prescribed in a Hindu Marriage Register kept for the purpose. The State Government may also make rules providing that the registration of marriages may be effected under the Indian Registration Act, 1908.'),
    
    (act_id, '9', 'Restitution of conjugal rights', 'When either the husband or the wife has, without reasonable excuse, withdrawn from the society of the other, the aggrieved party may apply, by petition to the district court, for restitution of conjugal rights and the court, on being satisfied of the truth of the statements made in such petition and that there is no legal ground why the application should not be granted, may decree restitution of conjugal rights accordingly.'),
    
    (act_id, '10', 'Judicial separation', 'Either party to a marriage, whether solemnised before or after the commencement of this Act, may present a petition praying for a decree for judicial separation on any of the grounds specified in sub-section (1) of section 13, and in the case of a wife also on any of the grounds specified in sub-section (2) thereof, as grounds on which a petition for divorce might have been presented. Where a decree for judicial separation has been passed, it shall no longer be obligatory for the petitioner to cohabit with the respondent, but the court may, on the application by petition of either party and on being satisfied of the truth of the statements made in such petition, rescind the decree if it considers it just and reasonable to do so.'),
    
    (act_id, '11', 'Void marriages', 'Any marriage solemnised after the commencement of this Act shall be null and void and may, on a petition presented by either party thereto against the other party, be so declared by a decree of nullity if it contravenes any one of the conditions specified in clauses (i), (iv) and (v) of section 5.'),
    
    (act_id, '12', 'Voidable marriages', 'Any marriage solemnised, whether before or after the commencement of this Act, shall be voidable and may be annulled by a decree of nullity on any of the following grounds, namely: (a) that the marriage has not been consummated owing to the impotence of the respondent; or (b) that the marriage is in contravention of the condition specified in clause (ii) of section 5; or (c) that the consent of the petitioner, or where the consent of the guardian in marriage of the petitioner was required under section 5 as it stood immediately before the commencement of the Child Marriage Restraint (Amendment) Act, 1978, the consent of such guardian was obtained by force or fraud; or (d) that the respondent was at the time of the marriage pregnant by some person other than the petitioner.'),
    
    (act_id, '13', 'Divorce', '(1) Any marriage solemnised, whether before or after the commencement of this Act, may, on a petition presented by either the husband or the wife, be dissolved by a decree of divorce on the ground that the other party (i) has, after the solemnization of the marriage, had voluntary sexual intercourse with any person other than his or her spouse; or (ii) has, after the solemnization of the marriage, treated the petitioner with cruelty; or (iii) has deserted the petitioner for a continuous period of not less than two years immediately preceding the presentation of the petition; or (iv) has ceased to be a Hindu by conversion to another religion; or (v) has been incurably of unsound mind, or has been suffering continuously or intermittently from mental disorder of such a kind and to such an extent that the petitioner cannot reasonably be expected to live with the respondent; or (vi) has been suffering from a virulent and incurable form of leprosy; or (vii) has been suffering from venereal disease in a communicable form; or (viii) has renounced the world by entering any religious order; or (ix) has not been heard of as being alive for a period of seven years or more by those persons who would naturally have heard of it, had that party been alive. (2) A wife may also present a petition for the dissolution of her marriage by a decree of divorce on the ground (i) in the case of any marriage solemnized before the commencement of this Act, that the husband had married again before such commencement or that any other wife of the husband married before such commencement was alive at the time of the solemnization of the marriage of the petitioner; or (ii) that the husband has, since the solemnization of the marriage, been guilty of rape, sodomy or bestiality; or (iii) that in a suit under section 18 of the Hindu Adoptions and Maintenance Act, 1956, or in a proceeding under section 125 of the Code of Criminal Procedure, 1973, a decree or order, as the case may be, has been passed against the husband awarding maintenance to the wife notwithstanding that she was living apart and that since the passing of such decree or order, cohabitation between the parties has not been resumed for one year or upwards; or (iv) that her marriage (whether consummated or not) was solemnized before she attained the age of fifteen years and she has repudiated the marriage after attaining that age but before attaining the age of eighteen years.'),
    
    (act_id, '13A', 'Alternate relief in divorce proceedings', 'In any proceeding under this Act, on a petition for dissolution of marriage by a decree of divorce, except in so far as the petition is founded on the grounds mentioned in clauses (ii), (vi) and (vii) of sub-section (1) of section 13, the court may, if it considers it just so to do having regard to the circumstances of the case, pass instead a decree for judicial separation.'),
    
    (act_id, '13B', 'Divorce by mutual consent', 'Subject to the provisions of this Act a petition for dissolution of marriage by a decree of divorce may be presented to the district court by both the parties to a marriage together, whether such marriage was solemnized before or after the commencement of the Marriage Laws (Amendment) Act, 1976, on the ground that they have been living separately for a period of one year or more, that they have not been able to live together and that they have mutually agreed that the marriage should be dissolved. On the motion of both the parties made not earlier than six months after the date of the presentation of the petition referred to in sub-section (1) and not later than eighteen months after the said date, if the petition is not withdrawn in the meantime, the court shall, on being satisfied, after hearing the parties and after making such inquiry as it thinks fit, that a marriage has been solemnized and that the averments in the petition are true, pass a decree of divorce declaring the marriage to be dissolved with effect from the date of the decree.'),
    
    (act_id, '14', 'No petition for divorce to be presented within one year of marriage', 'Notwithstanding anything contained in this Act, it shall not be competent for any court to entertain any petition for dissolution of a marriage by a decree of divorce, unless at the date of the presentation of the petition one year has elapsed since the date of the marriage: Provided that the court may, upon application made to it in accordance with such rules as may be made by the High Court in that behalf, allow a petition to be presented before one year has elapsed since the date of the marriage on the ground that the case is one of exceptional hardship to the petitioner or of exceptional depravity on the part of the respondent, but if it appears to the court at the hearing of the petition that the petitioner obtained leave to present the petition by any misrepresentation or concealment of the nature of the case, the court may, if it pronounces a decree, do so subject to the condition that the decree shall not have effect until after the expiry of one year from the date of the marriage or may dismiss the petition without prejudice to any petition which may be brought after the expiration of the said one year upon the same or substantially the same facts as those alleged in support of the petition so dismissed.'),
    
    (act_id, '15', 'Divorced persons when may marry again', 'When a marriage has been dissolved by a decree of divorce and either there is no right of appeal against the decree or, if there is such a right of appeal, the time for appealing has expired without an appeal having been presented, or an appeal has been presented but has been dismissed, it shall be lawful for either party to the marriage to marry again.'),
    
    (act_id, '16', 'Legitimacy of children of void and voidable marriages', 'Notwithstanding that a marriage is null and void under section 11, any child of such marriage who would have been legitimate if the marriage had been valid, shall be legitimate, whether such child is born before or after the commencement of the Marriage Laws (Amendment) Act, 1976, and whether or not a decree of nullity is granted in respect of that marriage under this Act and whether or not the marriage is held to be void otherwise than on a petition under this Act. Where a decree of nullity is granted in respect of a voidable marriage under section 12, any child begotten or conceived before the decree is made who would have been the legitimate child of the parties to the marriage if it had been dissolved instead of being annulled shall be deemed to be their legitimate child notwithstanding the decree of nullity.'),
    
    (act_id, '17', 'Punishment of bigamy', 'Any marriage between two Hindus solemnized after the commencement of this Act is void if at the date of such marriage either party had a husband or wife living; and the provisions of sections 494 and 495 of the Indian Penal Code, 1860, shall apply accordingly.'),
    
    (act_id, '18', 'Punishment for contravention of certain other conditions for a Hindu marriage', 'Every person who procures a marriage of himself or herself to be solemnized under this Act in contravention of the conditions specified in clauses (iii), (iv), and (v) of section 5 shall be punishable with simple imprisonment which may extend to one month, or with fine which may extend to one thousand rupees, or with both.'),
    
    (act_id, '19', 'Court to which petition shall be presented', 'Every petition under this Act shall be presented to the district court within the local limits of whose ordinary original civil jurisdiction (i) the marriage was solemnized, or (ii) the respondent, at the time of the presentation of the petition, resides, or (iii) the parties to the marriage last resided together, or (iiia) in case the wife is the petitioner, where she is residing on the date of presentation of the petition, or (iv) the petitioner is residing at the time of the presentation of the petition, in a case where the respondent is, at that time, residing outside the territories to which this Act extends, or has not been heard of as being alive for a period of seven years or more by those persons who would naturally have heard of him if he were alive.'),
    
    (act_id, '20', 'Contents and verification of petitions', 'Every petition presented under this Act shall state as distinctly as the nature of the case permits the facts on which the claim to relief is founded and, except in a petition under section 11, shall also state that there is no collusion between the petitioner and the other party to the marriage. The statements contained in every petition shall be verified by the petitioner or some other competent person in the manner required by law for the verification of plaints.'),
    
    (act_id, '21', 'Application of Act 5 of 1908', 'Subject to the other provisions contained in this Act and to such rules as the High Court may make in this behalf, all proceedings under this Act shall be regulated, as far as may be, by the Code of Civil Procedure, 1908.'),
    
    (act_id, '21A', 'Power to transfer petitions in certain cases', 'Where (a) a petition under this Act has been presented to a district court having jurisdiction by a party to a marriage praying for a decree for judicial separation under section 10 or for a decree of divorce under section 13, and (b) another petition under this Act has been presented thereafter by the other party to the marriage praying for a decree for judicial separation under section 10 or for a decree of divorce under section 13 on any ground, whether in the same district court or in a different district court, in the same State or in a different State, the petitions shall be dealt with as specified in sub-section (2). In a case where sub-section (1) applies, (a) if the petitions are presented to the same district court, both the petitions shall be tried and heard together by that district court; (b) if the petitions are presented to different district courts, the petition presented later shall be transferred to the district court in which the earlier petition was presented and both the petitions shall be heard and disposed of together by the district court in which the earlier petition was presented.'),
    
    (act_id, '21B', 'Special provision relating to trial and disposal of petitions under the Act', 'The trial of a petition under this Act shall, so far as is practicable consistently with the interests of justice in respect of the trial, be continued from day to day until its conclusion unless the court finds the adjournment of the trial beyond the following day to be necessary for reasons to be recorded in writing. Every petition under this Act shall be tried as expeditiously as possible and endeavour shall be made to conclude the trial within six months from the date of service of notice of the petition on the respondent.'),
    
    (act_id, '21C', 'Documentary evidence', 'Notwithstanding anything in any enactment to the contrary, no document shall be inadmissible in evidence in any proceeding at the trial of a petition under this Act on the ground that it is not duly stamped or registered.'),
    
    (act_id, '22', 'Proceedings to be in camera and may not be printed or published', 'Every proceeding under this Act shall be conducted in camera and it shall not be lawful for any person to print or publish any matter in relation to any such proceeding except a judgment of the High Court or of the Supreme Court printed or published with the previous permission of the court.'),
    
    (act_id, '23', 'Decree in proceedings', 'In any proceeding under this Act, whether defended or not, if the court is satisfied that (a) any of the grounds for granting relief exists and the petitioner is not in any way taking advantage of his or her own wrong or disability for the purpose of such relief, and (b) where the ground of the petition is the ground specified in clause (i) of sub-section (1) of section 13, the petitioner has not in any manner been accessory to or connived at or condoned the act or acts complained of, or where the ground of the petition is cruelty, the petitioner has not in any manner condoned the cruelty, and (bb) when a divorce is sought on the ground of mutual consent, such consent has not been obtained by force, fraud or undue influence, and (c) the petition is not presented or prosecuted in collusion with the respondent, and (d) there has not been any unnecessary or improper delay in instituting the proceeding, and (e) there is no other legal ground why relief should not be granted, then, and in such a case, but not otherwise, the court shall decree such relief accordingly.'),
    
    (act_id, '23A', 'Relief for respondent in divorce and other proceedings', 'In any proceeding for divorce or judicial separation or restitution of conjugal rights, the respondent may not only oppose the relief sought on the ground of petitioners adultery, cruelty or desertion, but also make a counter-claim for any relief under this Act on that ground; and if the petitioners adultery, cruelty or desertion is proved, the court may give to the respondent any relief under this Act to which he or she would have been entitled if he or she had presented a petition seeking such relief on that ground.'),
    
    (act_id, '24', 'Maintenance pendente lite and expenses of proceedings', 'Where in any proceeding under this Act it appears to the court that either the wife or the husband, as the case may be, has no independent income sufficient for her or his support and the necessary expenses of the proceeding, it may, on the application of the wife or the husband, order the respondent to pay to the petitioner the expenses of the proceeding, and monthly during the proceeding such sum as, having regard to the petitioners own income and the income of the respondent, it may seem to the court to be reasonable.'),
    
    (act_id, '25', 'Permanent alimony and maintenance', 'Any court exercising jurisdiction under this Act may, at the time of passing any decree or at any time subsequent thereto, on application made to it for the purpose by either the wife or the husband, as the case may be, order that the respondent shall pay to the applicant for her or his maintenance and support such gross sum or such monthly or periodical sum for a term not exceeding the life of the applicant as, having regard to the respondents own income and other property, if any, the income and other property of the applicant, the conduct of the parties and other circumstances of the case, it may seem to the court to be just, and any such payment may be secured, if necessary, by a charge on the immovable property of the respondent.'),
    
    (act_id, '26', 'Custody of children', 'In any proceeding under this Act, the court may, from time to time, pass such interim orders and make such provisions in the decree as it may deem just and proper with respect to the custody, maintenance and education of minor children, consistently with their wishes, wherever possible, and may, after the decree, upon application by petition for the purpose, make from time to time, all such orders and provisions with respect to the custody, maintenance and education of such children as might have been made by such decree or interim orders in case the proceeding for obtaining such decree were still pending, and the court may also from time to time revoke, suspend or vary any such orders and provisions previously made.'),
    
    (act_id, '27', 'Disposal of property', 'In any proceeding under this Act, the court may make such provisions in the decree as it deems just and proper with respect to any property presented, at or about the time of marriage, which may belong jointly to both the husband and the wife.'),
    
    (act_id, '28', 'Appeals from decrees and orders', 'All decrees made by the court in any proceeding under this Act shall, subject to the provisions of sub-section (3), be appealable as decrees of the court made in the exercise of its original civil jurisdiction, and every such appeal shall lie to the court to which appeals ordinarily lie from the decisions of the court given in the exercise of its original civil jurisdiction. Orders made by the court in any proceeding under this Act under section 25 or section 26 shall, subject to the provisions of sub-section (3), be appealable if they are not interim orders, and every such appeal shall lie to the court to which appeals ordinarily lie from the decisions of the court given in the exercise of its original civil jurisdiction. There shall be no appeal under this section on the subject of costs only.'),
    
    (act_id, '28A', 'Enforcement of decrees and orders', 'All decrees and orders made by the court in any proceeding under this Act shall be enforced in the like manner as the decrees and orders of the court made in the exercise of its original civil jurisdiction for the time being in force.'),
    
    (act_id, '29', 'Savings', 'A marriage solemnized between Hindus before the commencement of this Act, which is otherwise valid, shall not be deemed to be invalid or even to have been invalid by reason only of the fact that the parties thereto belonged to the same gotra or pravara or belonged to different religions, castes or subdivisions of the same caste. Nothing contained in this Act shall be deemed to affect any right recognized by custom or conferred by any special enactment to obtain the dissolution of a Hindu marriage, whether solemnized before or after the commencement of this Act. Nothing contained in this Act shall be deemed to affect any proceeding under any law for the time being in force for declaring any marriage to be null and void or for annulling or dissolving any marriage or for judicial separation pending at the commencement of this Act, and any such proceeding may be continued and determined as if this Act had not been passed. Nothing contained in this Act shall be deemed to affect the provisions contained in the Special Marriage Act, 1954, with respect to marriages between Hindus solemnized under that Act, whether before or after the commencement of this Act.'),
    
    (act_id, '30', 'Repeals', '[Repealed by the Repealing and Amending Act, 1960 (58 of 1960), section 2 and First Schedule.]');

END $$;